[client]
showErrorDetails = false
toolbarMode = "minimal"

[logger]
level = "info"

[server]
enableCORS = true
enableXsrfProtection = true
maxMessageSize = 200

[browser]
gatherUsageStats = false
serverAddress = "localhost"
